name: Zoe L. Lam 🌊
tagline: Physics and Computer Science Student at HKU
career-objective: 👽 Hello there! I am a second-year student at The University of Hong Kong, majoring in Physics and Computer Science. My fields of interest include learning about deep learning architectures and algorithms, as well as how AI can work together with quantum computers in the future (Quantum ML).
color-theme: blue # red or blue
avatar-filename: profile.png # Change to your avatar's filename
url: zl0618.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: zoelam1215@outlook.com
  github: 
    visibility: true
    handle: zl0618
  linkedin: 
    visibility: true
    handle: zl0618
  twitter: 
    visibility: false
    handle: something

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  projects: 
    label: Projects
    visibility: true
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: false
  skills: 
    label: Skills
    visibility: true
  publications: 
    label: Publications
    visibility: false
  volunteerexperience: 
    label: Volunteer Experience
    visibility: false
  certifications: 
    label: Certifications
    visibility: false
  achievements: 
    label: Achievements
    visibility: false

navigation:
navigation:
- title: About
  url: /
- title: Blog
  url: /blog/
- title: Contact
  url: /contact


include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X
